name: Deploy to Azure
on:
  push:
    branches:
      - master

env:
  AZURE_INDEX_DOCUMENT_NAME: "index.html"
  AZURE_ERROR_DOCUMENT_NAME: ""
  NODE_VERSION: "10.x"
  SOURCE_DIR: "./vuepress/dist"
  VUE_APP_GITHUB_CLIENT_ID: ${{ secrets.VUE_APP_GITHUB_CLIENT_ID }}
  VUE_APP_GITHUB_CLIENT_SECRET: ${{ secrets.VUE_APP_GITHUB_CLIENT_SECRET }}
  VUE_APP_GOOGLE_TAG_MANAGER: ${{ secrets.VUE_APP_GOOGLE_TAG_MANAGER }}
  VUE_APP_ALGOLIA_API_KEY: ${{ secrets.VUE_APP_ALGOLIA_API_KEY }}
  VUE_APP_ALGOLIA_INDEX_NAME: ${{ secrets.VUE_APP_ALGOLIA_INDEX_NAME }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Get latest code"
        uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "npm install, build, and test"
        run: |
          # Build and test the project
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: "Deploy to Azure WebApp"
        uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: ${{ env.SOURCE_DIR }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_INDEX_DOCUMENT_NAME: ${{ env.AZURE_INDEX_DOCUMENT_NAME }}
          AZURE_ERROR_DOCUMENT_NAME: ${{ env.AZURE_ERROR_DOCUMENT_NAME }}
