name: Deploy to Azure
on:
  push:
    branches:
      - master

env:
  NODE_VERSION: "10.x"
  SOURCE_DIR: "./site/vuepress/dist"
  VUE_APP_GITHUB_CLIENT_ID: ${{ secrets.VUE_APP_GITHUB_CLIENT_ID }}
  VUE_APP_GITHUB_CLIENT_SECRET: ${{ secrets.VUE_APP_GITHUB_CLIENT_SECRET }}
  VUE_APP_GOOGLE_TAG_MANAGER: ${{ secrets.VUE_APP_GOOGLE_TAG_MANAGER }}
  VUE_APP_ALGOLIA_API_KEY: ${{ secrets.VUE_APP_ALGOLIA_API_KEY }}
  VUE_APP_ALGOLIA_INDEX_NAME: ${{ secrets.VUE_APP_ALGOLIA_INDEX_NAME }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Get latest code"
        uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "npm install, build, and test"
        run: |
          # Build and test the project
          cd site
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: "Deploy to Azure Storage"
        uses: lauchacarro/Azure-Storage-Action@master
        with:
          enabled-static-website: "true"
          folder: ${{ env.SOURCE_DIR }}
          connection-string: ${{ secrets.CONNECTION_STRING }}
